#生产环境
server:
  port: 9092
  ip: http://118.89.121.243
spring:
  config:
    activate:
      on-profile: prop
  datasource:
    druid:
      url: jdbc:mysql://118.89.121.243:3306/sqn_home_pro?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
    host: 118.89.121.243
    port: 6379
    password: 1234
files:
  upload:
    path: /home/sqn_home/files/

