#测试环境
server:
  port: 9090
  ip: http://localhost
spring:
  config:
    activate:
      on-profile: test

  datasource:
    druid:
      url: jdbc:mysql://mysql.test.cnzxa.cn:23306/bed?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
      username: user
      password: Comfab.088
#  redis:
#    host: localhost
#    port: 6379

files:
  upload:
    path: D:/springbootspace/springboot_vue_framework/springboot/src/main/resources/files/

mybatis-plus:
  configuration:
    #    #    开启MP的日志，标准输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl