#通用环境
#数据库配置
spring:
  #  admin client配置
  #  boot:
  #    admin:
  #      client:
  #        url: http://localhost:8080

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #Springfox 假设 Spring MVC 的路径匹配策略是 ant-path-matcher
  #格式化购书日期格式:方式一：以下配置开启；方式二：entity-Book中的Date类型字段上添加@JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")注解
  #  spring.jackson.date-format=yyyy-MM-dd
  #设置session的有效时长 86400s=1天
  session:
    timeout: 86400
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-circular-references: true

  #    切换配置版本
  profiles:
    active: dev


mybatis-plus:
  configuration:
    #    驼峰自动识别
    map-underscore-to-camel-case: true

#设置日志模板格式
logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: dev_server%d{yyyymmdd}_%i.log
  #    pattern:
  #     console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
#  admin client配置
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: "*"
##        开启所有端点
#    enabled-by-default: true

#自定义ip监测配置属性
#tools:
#  ip:
#    log-cycle: 3

server:
  servlet:
    session:
      timeout: 10s