#生产环境
server:
  port: 9092
  ip: http://101.34.51.46
spring:
  config:
    activate:
      on-profile: prop
  datasource:
    druid:
      url: jdbc:mysql://101.34.51.46:3306/sqn_home_pro?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
      username: root
      password: root
files:
  upload:
    path: /home/files/