#通用环境
#数据库配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #Springfox 假设 Spring MVC 的路径匹配策略是 ant-path-matcher
  #格式化购书日期格式:方式一：以下配置开启；方式二：entity-Book中的Date类型字段上添加@JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")注解
  #  spring.jackson.date-format=yyyy-MM-dd
  #设置session的有效时长 86400s=1天
  session:
    timeout: 86400
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  redis:
    #    host: 127.0.0.1
    #    port: 6379
    #    password: ''
    # 连接超时时间
    timeout: 3000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-circular-references: true

  #    切换配置版本
  profiles:
    active: dev


mybatis-plus:
  configuration:
    #    开启MP的日志，标准输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    驼峰自动识别
    map-underscore-to-camel-case: true
#  global-config:
#    db-config:
#      id自增策略，默认为雪花算法，也可由其他方式设置
#      id-type: auto

files:
  upload:
    #    path: /home/files/
    path: D:/springbootspace/springboot_vue_framework/springboot/src/main/resources/files/


---
#开发环境
server:
  port: 9090
  ip: http://localhost
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/sqn_home?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
      username: root
      password: root

files:
  upload:
    path: D:/springbootspace/springboot_vue_framework/springboot/src/main/resources/files/
---
#测试环境

---
#生产环境
server:
  port: 9092
  ip: http://101.34.51.46
spring:
  config:
    activate:
      on-profile: prop
  datasource:
    druid:
      url: jdbc:mysql://101.34.51.46:3306/sqn_home_pro?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
      username: root
      password: root
files:
  upload:
    path: /home/files/